### ISSUE TITLE
Merge back to distcc?

### ISSUE THREAD

**Issue by thedrow** [icecc/icecream#138]
Hi, distcc maintainer here.
What do you guys think about merging this back upstream?

**Comment by HenryMiller1** [comment]
In theory I'm in favor of the idea, but I think you will find that in the years since the two code bases diverged there have been enough changes as to make it a non-trivial task.

icecc doesn't get much attention from maintainers (there are a number of open pull requests - nothing merged in more than half a year), it appears distcc gets more/better maintenance. If you can add a server to distcc it would solve the main reason people prefer icecc. (I'm surprised that hasn't been done yet)

**Comment by coolo** [comment]
As Henry already mentioned, icecc development stalled. From time to time there are people with new ideas, but they fade out quickly ;(

But distcc and icecc have two different use cases from what I can see. distcc is optimized for easy setup and small adminstration overhead, while icecc is optimized to do load balancing in large farms with tons of different systems. At suse we have > 100 machines acting as server and client - and icecc still works great for that despite the development being in maintenance.

So I'm not sure how you envision that merging back

**Comment by thedrow** [comment]
Merging this back might just mean feature parity with what icecream currently provides or merging some of the code directly to distcc.
I think that the entire Linux community will gain from one tool that is able to distribute compilation of large C/C++ components that provides more flexibility and allows you to grow from the easy to setup distcc type of deployment to the 100 machines build farm that icecc provides.
Are there more features that diverged from distcc except for the server/client architecture?

**Comment by ossilator** [comment]
as far as i know, icecc has no other outstanding features, and i know that it lags behind distcc in some areas (distcc now support windows, right?).

i don't think the audiences are all that disparate. icecc is pretty much zero-conf. in fact, it is more zero-conf than distcc. the one thing that would make it even better would be some automatic election system for the schedulers, so they don't conflict if multiple are started.

as far as big feature requests go, i'd like to see a distributed version of ccache built into icecc - maybe distcc already has that?

anyway, the status quo means that nobody will help you upstreaming icecc changes, and even less will there be a competing effort to update icecc with more recent distcc code (which would be effectively the same, just with possibly different preferences regarding which redundant code to keep). so, happy hacking! ;)

**Comment by coolo** [comment]
I'm not sure if distcc supports building in automatically created and transferred chroots nowadays?

**Comment by HenryMiller1** [comment]
@thedrow Are you doing anything about this?  I'm not sure if this issue should remain open or not.

**Comment by thedrow** [comment]
I'm not doing anything about this issue, unfortunately. I was hoping someone will volunteer to do this.
In any case, I think it's safe to close this issue for now.

**Comment by ossilator** [comment]
i think we should re-open this. there are several other issues open where the natural reaction would be "yeah, but why don't you invest in merging back into distcc instead?". so even if nobody actually works on this, it's still a valid item.

**Comment by HenryMiller1** [comment]
@thedrow 

I'm thinking about opening issues on distcc for each feature in icecream that distcc lacks, and a milestone overall to track them.  Does this seem reasonable?

Note that I know icecream well, and distcc almost none. I'm not expecting that things be implemented in the same way as icecream, just that ultimately the same features that icecream has work. Right now distcc is not compatible with my use case, even though I think pump mode would greatly help my use case.

**Comment by HenryMiller1** [comment]
Of course the problem of doing the work is still open. I'm hoping that by documenting the things we want it might inspire someone with time to work on it.

**Comment by timofonic** [comment]
@HenryMiller1  That's great! Any news?

I also found other similar projects, most of them abandoned
* [d2cc](https://bitbucket.org/mgorny/d2cc)
* [shadowman](https://github.com/mgorny/shadowman): A somewhat related project aimed at Gentoo.

Icecream/icecc is quite active thee days? What about merge both projects? They added clang (llvm?) support too. I wonder if distcc/icecc could be expanded for lots more of languages.

PS: What about distributed serverless compiling and checking with something similar like [gitian](https://gitian.org)?

**Comment by HenryMiller1** [comment]
@timofonic no news. This needs someone with some time to actually do the work.

There are a number of features we both have that work differently. Someone needs to figure how to merge those - remembering that this is a matter of compromise. The obvious one is icecream has a central scheduler, which is required for some of our use cases, but makes a couple of their use cases impossible. Thus getting consensus on which way is best might be impossible (even supporting both has issues)

icecc is not particularly active. This weekend we had a couple commits, and there is some indications that some people are doing something which might be merged in.  The same seems to apply to distcc. Both are fairly mature projects - most of the features anybody might need were implemented 10+ years ago, so it isn't a surprise that neither is active.

Doing this work is probably a good job for someone in google summer of code (though I don't know how much can actually be done in the timeframe)

**Comment by llunak** [comment]
I think there's not much point in keeping this open. If nothing else, it should be in distcc's bugzilla (or whatever). The codebases are so different that "merging back" to distcc efectively means writing it more or less from scratch. And I don't quite see anyone here having the motivation to write code for unfamiliar codebase (like, what would e.g. I have from it, learning a new codebase in a language that I like less and writing once again code I've already written?).

Besides, what would anyone get from doing this, when icecream simply works? I'm not that familiar with distcc, but from what I can see, distcc's extra features are only ssh support, cygwin support and pump mode. While nice, I don't see high demand for the first two, and the last one reportedly made a difference only in the times when gcc's preprocessor was slow (moreover, I tried this back in the sendheaders branch and, unless I messed up, doing this together with chroot just kills the performance). On the other hand, icecream's scheduler and chroot make icecream flexible and almost zero setup, unlike distcc.

Given that both icecream and distcc are low-activity projects now, I don't find this worth it in general, nor see the motivation for distcc being the one that receives the effort.

**Comment by ossilator** [comment]
arguably, this issue should be retitled "merge interesting parts from newer distcc", and distcc can have a complementary issue. depending on which work actually _does_ get done, the maintainers of the other project could declare theirs obsolete if they were satisfied with the outcome.

as far as features go:
- i think the reason why pump mode has become less significant is the pervasiveness of multi-core cpus, but according to #285 it's still relevant. also, the infrastructure needed to implement this feature is an excellent basis for distributed compilation with precompiled headers, and for distributed caching. i see that [you considered these](https://groups.google.com/d/msg/icecream-users/DOwPfUZs5ro/r5J_3yN6XsUJ), but i'll contest the conclusion - chroot'ing should have no major adverse impact when done right (you don't need to re-create the roots from scratch each time, as you populate them, so you know what's inside), and PCHs nowadays give quite a boost for c++.
- i can see how the windows support isn't of particular interest for suse (do you still work there?), but we at qt could certainly make good use of it. of course, the relevance of this is prospectively diminished by WSL (#206), and the full monty would require msvc support anyway (#201).

it would probably make sense to replace this issue with per-feature ones.

**Comment by llunak** [comment]
The first paragraph is about what I meant to say, although I'd rather phrase it as "close this and if somebody sees something missing that distcc has, make an issue for it". As for the rest:

- AFAIK the reason why pump has become less significant is because gcc's preprocessor no longer performs rather poorly. Also note http://wsl.softwarelivre.org/2012/0017/39.pdf (the only comparison of icecream vs distcc I could find), which claims that pump mode in fact makes things a bit slower. And I've just commented on #285 because I find its claims unfounded. I think the only area where pump mode may realistically improve performance is by reducing the number of data sent to the remotes (headers just sent once). I doubt a bit it makes any noticeable CPU difference, since you need to find out the included headers somehow, and unless one goes for a hacky grep or somesuch, it's probably not going to make a bit difference from just finding this out from the preprocessor (note that icecream git now skips full preprocessing even for gcc by using -fdirectives-only). So until somebody can prove that something like pump mode still matters, I don't see this worth bothering.

- As for PCH, I most likely did a mistake back then, since I now can see they do provide some performance boost. But that may be solved in a much simpler way by just shipping the whole PCH to the remote (well, at least for clang, where the .pch is not significantly larger than the .ii, gcc's .gch are huge). And one way or another, the cost of using PCH remotely may be in fact larger than just ignoring PCH for remote builds.

- I didn't write windows support, I wrote cygwin. AFAICT distcc supports only cygwin+gcc, which is what I don't find of particular interest to many people. There have been some attempts at cl support, but since they apparently didn't make it into distcc proper, I guess they don't count. So while cl support would be nice, it's unrelated to the distcc issue.

**Comment by ossilator** [comment]
- the point about pump mode needing include pre-scanning is a very valid one - [i commented on that before](https://groups.google.com/d/msg/icecream-users/jn5-w39aLE4/Y1LP8v-bBgAJ). the proposed solution is [quite relevant for advanced build tools](https://bugreports.qt.io/browse/QBS-22) as well.
but there is also another reason why you'd want to distribute the actual sources instead of the preprocessed file: the result can be actually different (warnings about dead code; there was some ping-pong in the icecc repo related to attempts at addressing this issue).

- you can't argue against pch distribution by proposing a simplified solution and pointing out that this one is inefficient. ;)

- i thought i've seen native winsock code in the repository, but that must have been some other project i've been inspecting in this context (many years ago), so that point is moot. just cygwin support is a rather minor feature, and thus not a particularly relevant argument in favor of a merge.

**Comment by llunak** [comment]
You're a bit out-of-date on the issue of icecc and local preprocessing :). With Clang icecc has been doing preprocessing remotely for at least 3 years, and current git does similarly with Gcc. As for remote PCH, I expect that all methods of remote PCH are likely to have costs outweighting the gains, but feel free to prove me wrong.

**Comment by ossilator** [comment]
it is? i suppose it's done in two passes, #includes locally and the rest remotely, which i suppose works, but is still somewhat less efficient than not doing duplicate work.
i'm not even sure how the statement about PCH _could_ be true.
your working thesis seems to be that getting files to the remote nodes and persisting/re-using them reliably is inherently expensive. why would it, beyond the implementation problems of your approach?

**Comment by llunak** [comment]
Closing this. There's nobody to do the work, which is what matters the most here, so this whole issue is just theoretical.

If somebody wants to actually do the work, feel free to. If you miss a specific feature from distcc, please report a specific feature request.
