### ISSUE TITLE
Will icecc only balance load if only number of jobs exceed the number of cores on system?

### ISSUE THREAD

**Issue by pold500** [icecc/icecream#186]
Will icecc only balance load if only number of jobs exceed the number of cores on system?

**Comment by HenryMiller1** [comment]
Iceccc has no concept of how much load is on your system and will always attempt to load balance. This is generally correct: this is probably the first of many jobs coming so icecc should make the job remote so local resources can be used to prepare the next compiles. If you have less compile jobs than resources on your local machine it is probably faster to work remotely, but icecc has no way to know that is happening.

**Comment by pold500** [comment]
@ HenryMiller1 "Iceccc has no concept of how much load is on your system and will always attempt to load balance"

I don't understand, how it can distribute the load if it doesn't know how loaded is my system?
Let's say, I've 8 cores on my processor and total CPU load is 1%. I start the build without -j switch, where the load will go?

**Comment by HenryMiller1** [comment]
icecream doesn't know that you are not using the -j switch.  That switch is passed to make, but make does not pass it on to icecream.  (some versions of make might put it in an environment variable - but icecream doesn't read that variable)

icecream will always assume that you have passed a high -j count to make, and try to distribute the load to other systems.  In your no -j case this is the wrong thing, but icecream does not know that.

I did misspoke a bit when I said icecream has no concept of load.  The icecream scheduler knows the load of all systems on the network and will use that to decide which machines you should distribute your workload to.  What I meant was icecream does not use local load to decide it should not distribute jobs. In fact the algorithm is designed to assume a high -j count and so it should distribute all work if possible so that the local CPUs are free to do other work that cannot be distributed.

**Comment by pold500** [comment]
@HenryMiller1 thank you for clarification, so, in simple words, icecc will *always* distribute the load no matter of j switch, right?

**Comment by HenryMiller1** [comment]
Correct. The load is always distributed.
