### ISSUE TITLE
What would take to support MSBuild too?

### ISSUE THREAD

**Issue by ohhmm** [icecc/icecream#201]
Would be nice to parallel Visual C++

**Comment by HenryMiller1** [comment]
A lot of work is the short answer.

First, what is the legal situation? I'd hate for you to go through all this work and then have Microsoft have us remove this because for some reason nobody is allowed to use visual C++ in this way...  (I know that other distributed build tools support Visual C++, but they might require that is be installed on each system already or something). I think this is just a formality check, but it should be mentioned.

If you had asked about cygwin there is a good change it works, though it might need to document how to configure it. (pull requests welcome). Visual c++ is going to be harder, but I recommend you start with cygwin as anything you learn here is something you can fix with a much smaller scope of where things might be going wrong.

The first step is to build on Windows. Right now we use autotools which isn't known to be Windows friendly. I would personally favor switching to cmake (I know cmake well, all I know about autotools is the name), but I don't know how the other developers feel about this.

Then you need to abstract the unixisms.  I don't know windows, so the following is a guess.  Fix the network code to compile, I'll point out issue #134 which ought to be considered as well if you touch the network.  Abstract the system load code to work in Windows. At this point everything should compile, run, and connect to the scheduler (which should also work).

I'd pause here and port icemon now, you will want it for debugging.

Now you need to get icecc-create-environment working - it needs to figure out how to package up visual C++ and whatever else is needed to run visual C++.  Along with this modify icecc to call visual C++ instead of gcc (which might be enough to rename the compiler to gcc?)

Then you need to ensure that we can distinguish between Windows and linux hosts so you don't distributed visual C++ jobs to linux, or gcc jobs to windows (unless you have a gcc/clang cross compiler for windows packaged).

Don't forget to write tests for the above.

Now think hard: should the above be put into icecream, or a fork that is never merged back. 

On the fork side: What is the use case for Windows and linux(OSX) hosts connecting to the same scheduler? I don't expect to see visual C++ distributing to linux hosts.  It is theoretically possible to build gcc/clang for windows so that will compile for linux, but will anyone actually do this? Just change the default ports so that icecream and your fork can run on the same network and never see each other.

On the together side: for a future story I would like to make iceccd to be VM aware: IT makes me run Windows, but I do all my work in linux in a VM - configuring icecc in a VM is never right (describing all the issues would take a lot of space and I'd probably miss some special case). It would be nice if I could run iceccd on windows, and have it coordinate the work in all my VMs. I haven't figured out how to make this work but it is on my mind.

**Comment by HenryMiller1** [comment]
I should mention that the above is what I can think of. There are probably more issues.

**Comment by HenryMiller1** [comment]
Are you going to work on this? If not I'd like to close this issue, but if you are actually doing work I'll leave it open.

**Comment by iHateInventNames** [comment]
@Microsoft please, comment on this, is it legal?

**Comment by ossilator** [comment]
before you invest actual work in this, i would strongly recommend that you merge back to/from distcc - they have a working windows port, pump mode (fully remote operation), and whatnot.
some guys had a shot at msvc support, but it doesn't seem to have gotten far - https://wiki.cdot.senecacollege.ca/wiki/Distcc_With_MSVC

**Comment by HenryMiller1** [comment]
good point, there is desire on both the icecream and distcc side to merge back into one code base with the best of both world.

**Comment by HenryMiller1** [comment]
good point, there is desire on both the icecream and distcc side to merge back into one code base with the best of both worlds. It just needs someone to do the work.

**Comment by llunak** [comment]
While this would be nice to have, there are many technical (and legal) questions about the feasibility of this. So if you want to do the implementation, feel free to, but I personally consider this rather hard and bordering on being out of scope for Icecream because of the changes possibly involved, so unless somebody does the work, I don't see much point in keeping this open.
