### ISSUE TITLE
icecc on windows subsystem for linux?

### ISSUE THREAD

**Issue by qdot** [icecc/icecream#206]
Would there be any interest in trying to get icecc up and running on WSL, for working as a linux build node? As of the creators update for win10, icecream builds and runs (before creators update, it required a couple of patches so it wouldn't crash on start, and there was no chroot so it was kinda moot anyways), but has a lot of silent failures, so it'd probably take a lot of error annotation and debugging.

**Comment by HenryMiller1** [comment]
I'm not against it, but it requires a maintainer, otherwise even if you get it working the code is likely to bit rot.  A ci system and some tests would be welcome (your choice) to ensure that things continue to work in some fashion.

This feels like the first steps of issue #201, most of the comments there apply to this as well so I won't repeat them.  You should coordinate work with the author of that issue: perhaps on waffle.io?  (I've never used it, but it seems like it is better for this type of problem - if you don't like it you can disregard this suggestion)

**Comment by llunak** [comment]
Icecream now builds and runs on Cygwin (client part at least), so if you get WSL running too, why not. But given the lack of a follow-up, I take it this is not valid anymore.

**Comment by yw5aj** [comment]
Dear all,

I am trying to use `icecc` on Ubuntu 18.04 in WSL but faced challenges.

What I did:

* Use `sudo apt-get install icecc icecc-monitor` to install on both scheduler and node;
* On the scheduler, I ran both `sudo iceccd -d` and `sudo icecc-scheduler -d`;
* On the node, I start the daemon:
  * If I run  `iceccd -d`, then I can see the node in the scheduler's Icecream Monitor. However, the node is marked as "no remote";
  * If I run `sudo iceccd -d` then I would not even be able to see the node on my Icream Monitor.

Could anyone please point where can I start troubleshooting this?

Shawn

**Comment by llunak** [comment]
You can run each of the daemons with "-v -v -v" to get more log info. The "no remote" is presumably because iceccd requires chroot privileges. I don't know why the sudo one wouldn't work, but the logs should help (or post them here).

**Comment by llunak** [comment]
Oh, and please don't hijack issues for your reports, create a new one.

**Comment by yw5aj** [comment]
Oh sorry. I thought it'd be better to keep the same topic on the same thread. I'll open a new one now.

**Comment by yw5aj** [comment]
Opened https://github.com/icecc/icecream/issues/522 for my question separately.
