### ISSUE TITLE
tests run against striped binaries - santizers cannot do backtraces

### ISSUE THREAD

**Issue by HenryMiller1** [icecc/icecream#214]
Icecream tests run against the binaries that are installed.  Install strips these binaries, as a result sanitizers cannot find the symbols for the binaries and thus do not show a useful backtrace.

I was able to work around this by hardcoding in tests/test.sh prefix to be the path to my build directory, and then changing the path to iceccd, icecc, and icecc-scheduler to the appropriate paths in the build directory and get symbols from sanitizer backtraces.  

I think it is enough to make the above production ready, but I'm not sure

**Comment by llunak** [comment]
Please revert this.

I can see several problems with this:
- The filecap utility doesn't recognize an argument as a file unless it is passed an absolute path, but ${builddir} is a relative path. So this fails here.
- Calling filecap on the builddir binary installs capabilities on a file that may be later used for other purposes.
- The point of installing the whole testing setup is to check it as it will be used, not some builddir binaries in whatever state.

Finally, I don't even see the need for this, as the original reasoning seems bogus. "make install" under normal circumstances does not strip the binaries, otherwise e.g. distributions would be unable to split out debuginfo packages. If I run "make test" here, I can clearly see that make calls only "install -c", without the "-s" argument that would strip. So if you have such a problem, it appears your setup is broken.

**Comment by llunak** [comment]
Let me handle that elsewhere: https://github.com/icecc/icecream/pull/312 .
