### ISSUE TITLE
Incorrect scheduler_use_cs result when behind a NAT from scheduler

### ISSUE THREAD

**Issue by vvandy** [icecc/icecream#296]
If icecc-scheduler is running on a host outside of the NAT of iceccd, jobs sent to the local iceccd daemon will fail to run due to the mismatched remote_name.

iceccd will believe its remote name is its internal IP address, icecc-scheduler will see the external address.  It will attempt to compile as if it were an outside job, but iceccd will claim to be missing the environment, which never gets transferred.

There was a viable workaround for this in Issue #157 commit 6e9061c.  With that commit, you can set the external name, and scheduler_use_cs can properly detect this case.  However, this was reverted by commit 267159f, so now there is no way to inform iceccd of its external address.

**Comment by HenryMiller1** [comment]
commit 2e7bb99 replaced 6e9061c by having the scheduler tell the daemon when the compile job was sent back to the client.  I am using this behind a NAT extensively so I know it works (at least in some cases...)

Is your scheduler up to date? Running an out of date scheduler could cause this problem. Otherwise I need more information as this should "just work"

**Comment by HenryMiller1** [comment]
On second thought I am not sure what scheduler I'm running with when I test NAT.  However I think the direction that NAT should work without needing configuration options is correct so I don't want to return to the commit that was reverted.

**Comment by vvandy** [comment]
Sorry for the delay, I found we're running scheduler 1.0.90, I'll update and close if that fixes it.

**Comment by vvandy** [comment]
My mistake, our RHEL distributions have very old schedulers/compilers.  This is indeed fixed in 1.1.
