### ISSUE TITLE
Add option to preprocess C++ macros on slave machine to improve build performance

### ISSUE THREAD

**Issue by gang65** [icecc/icecream#386]
Problem description:
Currently during running icecc on two machines, all preprocessing is done on host machine.
It is bottleneck of overall performance of icecc, on projects with large amount of macro (like #include)

Steps to reproduce (tested on macOS):
The best way to reproduce the issue is:
- run icecc scheduler (`icecc-scheduler.service`) on Ubuntu machine
- run `iceccd` on host with maximum number of process set to 0 (`-m 0`) (I run it on macOS machine)
- run `iceccd` on slave normally (eg `-m 8`) (I run it on macOS machine)
- start build on host machine.

Actual result:
- The host machine have high load, even if compilation is made on slave machine
- The slave machine has low load

Expected result:
- Most of build load are redirected to Slave machine

**Comment by HenryMiller1** [comment]
Distcc has pump mode which does this. There is interest, and there have
been attempts to do this. It is questionable if it actually helps, and
so far nobody has had time to do it.
We will review your patches if you want to attempt it. That is all
anyone can promise, those who maintain ice cream either have found it
not helpful for their environment, or don't have time.
--
  Henry Miller
  hank@millerfarm.com



On Mon, Mar 26, 2018, at 7:15 AM, Bartosz wrote:
> Problem description:
>  Currently during running icecc on two machines, all preprocessing is
>  done on host machine.>  It is bottleneck of overall performance of icecc, on projects with
>  large amount of macro (like #include)> Steps to reproduce (tested on macOS):
>  The best way to reproduce the issue is:


>  * run icecc scheduler (icecc-scheduler.service) on Ubuntu machine
>  * run iceccd on host with maximum number of process set to 0 (-m 0)
>    (I run it on macOS machine)
>  * run iceccd on slave normally (eg -m 8) (I run it on macOS machine)
>  * start build on host machine.> Actual result:


>  * The host machine have high load, even if compilation is made on
>    slave machine
>  * The slave machine has low load> Expected result:


>  * Most of build load are redirected to Slave machine> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

Links:

  1. https://github.com/icecc/icecream/issues/386

**Comment by RedBeard0531** [comment]
Setting the environment variable `ICECC_REMOTE_CPP=1` should help a lot since it only does include processing locally and ships the heavy-weight preprocessing to the remote node. We use it for correctness, but it also helps a lot with performance. For some reason it makes a bigger difference with gcc (using `-fdirectives-only`) than on clang (using `-frewrite-includes`). I don't know what the minimum icecc version is that supports that flag, but if you are using gcc, you can just add `-fdirectives-only` to your build flags and it should just work.

**Comment by gang65** [comment]
Thank you all for fast response.
I have some spare time which I could use for improving icecc.

Do you know what else could improve build performance?
I'm also interesting in minimalizing the overhead on single machine, as according to numbers:
https://github.com/icecc/icecream#some-numbers
it is quite big.

**Comment by RedBeard0531** [comment]
@gang65 IMO the best thing you can do to improve build times with icecream is to improve the speed of clang's `-frewrite-includes` mode, since it seems to be the bottleneck in my experience. I've also seen network bandwidth be an issue, especially when shipping out the environments. Switching to better/faster compression may help here. lz4 and zstd may be interesting. xz is probably too CPU intensive to be worth it.

**Comment by gang65** [comment]
As I understand shipping environment is made only once just before the build starts.
If shipping environment is a bottleneck

**Comment by RedBeard0531** [comment]
@gang65 I got curious and just ran a test. Building the compiler tarballs with `zstd --ultra -22` is probably the best bet. It compresses a 56MB .tar down to 13MB vs 23MB with `gzip -9`. It also decompresses faster (0.153s vs 0.385s). It does take over twice as long to compress (22s vs 8s), but since that only happens when you upgrade your toolchain, that seems like a good tradeoff.

The reason that time spent shipping envs is an issue is because we have >40 hosts in our cluster, often with different environments, so it is common that by the time you go to build, someone has bumped your environment out of the remote nodes cache. https://github.com/icecc/icecream/issues/276 would be very helpful for us. If the remote nodes have your env, our build times can be as low as 1-2 minutes. If the env needs to be shipped out, it takes an extra ~15s or so, which is a large fraction of total build time.

**Comment by HenryMiller1** [comment]
Running a profiler would be an interesting exercise to see where
bottleneck is. I suspect that the largest source of overhead is
network delays which are inherent and so not something that you can do
anything about.
--
  Henry Miller
  hank@millerfarm.com



On Mon, Mar 26, 2018, at 9:13 AM, Bartosz wrote:
> Thank you all for fast response.
>  I have some spare time which I could use for improving icecc.


> Do you know what else could improve build performance?
>  I'm also interesting in minimalizing the overhead on single machine,
>  as according to numbers:> https://github.com/icecc/icecream#some-numbers
>  it is quite big.


> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/icecc/icecream/issues/386#issuecomment-376180328

**Comment by martinm82** [comment]
Regarding the toolchain: What about not using any toolchains and instead falling back to what is available on the host? 
On Linux we have a dockerized build environment which we control and can ensure that all nodes have the same version. Same applies for macOS.
This kind of fallback is as well implemented in distcc.

**Comment by RedBeard0531** [comment]
@martinm82 we have something similar (using AMIs rather than docker) for our real builds, but we don't use icecream for that since [evergreen](https://github.com/evergreen-ci/evergreen) already manages many machines. We use icecream for our developer builds and everyone runs their own OS with their own compilers so we can never use the native toolkit. Instead we made [both](https://github.com/RedBeard0531/mongo_module_ninja/blob/f9c6d630e5ebaebf9353c95431940397cc300200/build.py#L197-L265) of our [build systems](https://github.com/mongodb/mongo/blob/master/site_scons/site_tools/icecream.py) icecream-aware so that they can handle building the environment tarballs and adding `ICECC_VERSION` to the compile commands. This is what makes icecream usable for us while distcc could never work.

**Comment by llunak** [comment]
As said above, current git does this with ICECC_REMOTE_CPP=1.
