### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by zbraniecki** [icecc/icecream#391]
The master branch of icecream fixes a bug that prevented it from working in my environment with clang. Can we get a new release please?

**Comment by HenryMiller1** [comment]
I've been working with the idea of doing yearly releases in August. I will take community input on if we should release more often.

We don't get a lot of changes, and we are not a big project so I will object to releasing too often, but I don't know what too often is.

In order to get a release somebody needs to go through history and update NEWS with something relevant.

**Comment by zbraniecki** [comment]
Sooo, August? :)

**Comment by HenryMiller1** [comment]
Someone needs to write up a news file. 

--
  Henry Miller
  hank@millerfarm.com



On Mon, Aug 13, 2018, at 2:47 PM, Zibi Braniecki wrote:
> Sooo, August? :)


> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
Links:

  1. https://github.com/icecc/icecream/issues/391#issuecomment-412640823

**Comment by ossilator** [comment]
unless this is supposed to be a permanent task, it can be closed now.

**Comment by llunak** [comment]
Closing as per the previous comment.
