### ISSUE TITLE
Linux Kernel Assembly Macros

### ISSUE THREAD

**Issue by lsgunth** [icecc/icecream#428]
Hi,

As of v4.20-rc1 icecc (and distcc for that matter) can no longer be used to distribute a compile of the linux kernel for x86. See this [thread](https://lore.kernel.org/lkml/89262174-6f15-6116-e67f-436f7c1bfe99@deltatee.com/T/#u).

The problem is the kernel is now adding "-Wa,macros.s" argument to every compile option so that specific assembly macros can be used in inline assembly code across the kernel. When icecc sees this it forces a local compile and is thus useless for speeding up kernel compiles.

Is there any way this could be supported by icecc as there does not appear to be a good solution in the kernel?

Thanks,

Logan

**Comment by llunak** [comment]
The -Wa option (and the similar -Xassembler) are technically -Wa,<option> , and whatever is passed to it gets passed to the assembler by the compiler. Since icecc doesn't know what the option may possibly be, it makes sense that a local compilation is forced.
But for the specific case of -Wa,<file> this could be handled similarly to how -fplugin or Clang's -load are handled. See how the code in https://github.com/icecc/icecream/blob/cc8adcfd8f122e80b3fb9503ef653929586a03ed/client/arg.cpp#L234 checks that and adds those files to "extrafiles".
In fact, looking there at the code handling -Wa, it explicitly checks for the -Wa,<file> case and forces it to build locally, so that's where this handling should be added.

**Comment by lsgunth** [comment]
Thanks for the hints. I did find the -Wa handling but didn't see how the extrafiles worked. This makes it pretty straightforward to add support. I'll send a PR shortly.

Logan
