### ISSUE TITLE
GCC preprocessor with `-fdirectives-only` can break compilation with raw string literals

### ISSUE THREAD

**Issue by milianw** [icecc/icecream#451]
Example code:

```
int main()
{
    const auto vert = R"(
#hello)";
    return 0;
}
```

If you preprocess this with `gcc -E -fdirectives-only`, then it fails with:

```
test.cpp:4:2: error: invalid preprocessing directive #hello
 #hello)";
  ^~~~~
test.cpp:4:8: warning: missing terminating " character
 #hello)";
        ^
```

I'm reporting this here for others to find, but will will now also report a bug upstream for GCC. I don't know how icecream could solve this issue - it looks like a GCC bug to me.

**Comment by milianw** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88475

**Comment by llunak** [comment]
A GCC bug, not much we can do about this except you setting ICECC_REMOTE_CPP=0, or probably pull request #444 will silently rebuild locally.

**Comment by deriamis** [comment]
This is not actually a GCC bug, though it does invoke undefined behavior in GCC because violating a precondition of its use. The problem is that if icecream sees this argument on the command line, it gets passed to *both* the preprocessor and the compiler. The partial preprocessing this flag calls for is not idempotent, so it can cause build failures if used on source file that is already preprocessed. Now that Icecream is adding this argument to the remote preprocessor when `ICECC_REMOTE_CPP=1`, this has become more likely to happen.
