### ISSUE TITLE
NVCC support

### ISSUE THREAD

**Issue by incardon** [icecc/icecream#478]
Does it work with nvcc ? If not any idea to support this compiler in the future ?

**Comment by llunak** [comment]
There's no support for nvcc. Your second question is too vague to know what you mean exactly. If you're asking if somebody else will implement it, then I find it unlikely, because that requires somebody who'd use nvcc and have the motivation/skill to implement the support, and I'm not aware of anybody like that.
If you're saying that you would like to implement it and asking for hints, then you're welcome to try to do it. Icecream currently supports only gcc and clang, so if nvcc is used similarly enough to these, it should be a matter of special-casing nvcc where needed. Also note that icecc-create-env packages parts of the compiler and ships them to remote nodes, so you'd need to check if nvcc's license allows that.

**Comment by incardon** [comment]
> If you're asking if somebody else will implement it

Yes, this is what I was asking. And you completely answered the question, so thanks for the answer.

> If you're saying that you would like to implement it and asking for hints, then you're welcome to try to do it.

No. This is not what I was saying. But I am asking now. In particular I am a C/C++ developer using nvcc  willing to check the cost in term of work. And eventually try in the future to create a patch for it. I checked tutorials looked at the code structure, compiled in debug mode, and had a look at the testing suite to find a starting point. I thought that the client was a good starting point. Out of this "today play around" I am completely new to icecream.

 On the other hand you raised icecc-create-env that I completely missed. So ... if you have more advice I am listening ...

> Also note that icecc-create-env packages parts of the compiler and ships them to remote nodes, so you'd need to check if nvcc's license allows that.

Wow. I am not a lawer I think I would need help to discover it. I was wondering if the point 2.1.1 from Software License Agreement for NVIDIA CUDA Toolkit is good enough.

2.1.1 Usage Rights. Licensee may install and use multiple copies of the SOFTWARE on a shared computer or concurrently on different computers, and make multiple back-up copies of the SOFTWARE, solely for Licensee’s use within Licensee’s Enterprise. “Enterprise” shall mean individual use by Licensee or any legal entity (such as a corporation or university) and the subsidiaries it owns by more than 50 percent.

**Comment by llunak** [comment]
https://github.com/icecc/icecream/issues/470 has a very brief description from me of how Icecream works in principle. In your case you'd first need to find the commands you want to distribute, preferably start with something that'd be as close as possible to the simplest "gcc -c a.c -o a.o". Then primarily you need to handle client/ for the part that prepares the compiles locally and daemon/ (primarily daemon/workit.cpp) for the remote compilation. Generally searching for "clang" should point to most places where each compiler needs its own specific handling. It might also help to look at sources of https://ccache.dev/ as according to its docs it supports nvcc and it works sort of similarly to Icecream (it caches the builds instead of distributing them).

As for the legal part, I'm no lawyer either, but the part you quoted seems sufficient to me.

**Comment by llunak** [comment]
I hope I have answered your questions, so I think there's not much to do do about this issue. If you have more questions, please reopen and ask. For now, I'm closing this.
