### ISSUE TITLE
icecc-scheduler - Option to only link files

### ISSUE THREAD

**Issue by MrD2** [icecc/icecream#481]
Add an option to icecc-scheduler to only use compute to link the compiled files.

This makes sence for a distributed containerized environment where i want to reserve the scheduler container to link all the files and spawn N container workers to compile the code.

**Comment by llunak** [comment]
Sorry, I don't understand what you mean (or how is this different from #482 ).

**Comment by MrD2** [comment]
The idea here is that, i can use the scheduler only to run linking. 

As it works now, i launch the daemon on the scheduler and it assembles stuff, until i have enough worker nodes doing the assembly to overload the master with link jobs.

This allows me to reduce the scheduler compute resources to a minimum of  (lets say, 1 thread) and then scale the image vertically.

This is not that usefull though if you have https://github.com/icecc/icecream/issues/482

You can close if you want.

**Comment by llunak** [comment]
I think you're confusing scheduler with the client maching submitting jobs. A scheduler can be any machine that runs the extra daemon coordinating build jobs.
Either way, the scheduler tries to prefer remote nodes in case the compilation is parallel enough, in order to allow the submitter to spend the resources on doing jobs that cannot be distributed, such as linking. So in general this should already work. If you really want to limit usage on the submitter, you can configure its daemon to not allow remote jobs or to limit its allowed number of jobs.

**Comment by MrD2** [comment]
As far as i undestand, only one scheduler per network might be used at one time (its a 1 to many scheduler workers architecture)

Can i compile multiple projects at the same time, using the same scheduler? I tried it, didn't work.
Can i use 2 scheduler nodes to coordinate the workers together? How would this work if i don't have Broadcast available?

**Comment by HenryMiller1** [comment]
1 scheduler, many clients. Any client can compile at any time, even if others already are. This is a common use case and generally works well. You would need to give more details on why it didn't work for you, it works for me. 

-- 
 Henry Miller
 hank@millerfarm.com
