### ISSUE TITLE
[Documentation] distcc versus icecream: are there any trade offs when using icecream as opposed to distcc?

### ISSUE THREAD

**Issue by rubyFeedback** [icecc/icecream#502]
Hello there,

I was reading:

https://github.com/icecc/icecream#i-use-distcc-why-should-i-change

The impression that I get from reading this is that icecream is very similar to distcc, and actually may only have advantages (as far as the software is concerned; I assume distcc has one advantage in that more people use it right now).

Would it be possible to extend the section there, at the main README, to explain if there may be any drawbacks related to icecream itself (the software), as opposed to distcc (ignoring unknown bugs)? E. g. in particular when there is a distcc user who has no real preference for using distcc or icecream, whether switching to icecream would be trivial, without any disadvantage.

I know distcc a bit, but I know absolutely nothing about icecream (I actually found it from an ubuntu link to another package, oddly enough; not sure how I ended up here :D).

Please feel free to close this issue at any moment in time, no matter the reason(s)!

**Comment by llunak** [comment]
It's a question if somebody here actually knows enough about distcc to make such a comparison. The only thing that I'm aware of which distcc has and icecream doesn't is ssh support, which makes data transfer secure at a performance cost. Icecream sidesteps the whole issue by saying that it assumes a trusted network and if it's not then it's the user's responsibility to achieve it in any way the user sees to fit. I'm also not aware of any demand for that in icecream, so depending on the point of view it's even a question whether that is an advantage of distcc.

I myself don't see any advantage in using distcc instead of icecream, and I wouldn't know what to add in that suggested section, so I'm just going to close this issue. If this interests you, I suggest you try it out yourself and if you actually find something, then please report it and we can either improve icecream or add the issue to that section you linked.
