### ISSUE TITLE
Analog of distcc --randomize option?

### ISSUE THREAD

**Issue by baybal** [icecc/icecream#539]
Hello,

I noticed that icecc scheduler doesn't seem to be using any round robin, or load randomisation, and loads hosts sequentially.

![load pattern](https://i.ibb.co/vLbCpjG/Screenshot-2020-06-13-23-43-00.png "Load pattern")

Given that almost all modern CPUs throttle aggressively, I think it makes a lot of sense to maximise the use of "thermal mass" of the cluster.

**Comment by llunak** [comment]
Icecream is not distcc, it has a central scheduler that distributes jobs based on performance of nodes, so it doesn't need to use any simple distributing techniques like round-robin. And while it does load hosts sequentially, the sequence is ordered by host performance. Randomization would presumably just degrade performance.
What perhaps would make sense would be to improve the scheduler to consider TDP, but that already happens to some extent (https://github.com/icecc/icecream/blob/master/scheduler/scheduler.cpp#L311). So this issue is already handled or void (unless you have specific improvements in mind, preferably in the form of a pull request).
