### ISSUE TITLE
Travis-ci: builds are failing on AMD64

### ISSUE THREAD

**Issue by sanjaymsh** [icecc/icecream#564]
Hi,

The builds are failing on travis-ci for AMD64 with below error:

"
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/etc/asciidoc/docbook-xsl/manpage.xsl" "/home/travis/build/sanjaymsh/icecream/doc/icerun.xml" returned non-zero exit status 5
Makefile:610: recipe for target 'icerun.1' failed
make[2]: *** [icerun.1] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:430: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
Makefile:362: recipe for target 'all' failed
make: *** [all] Error 2
The command "make -s -j $(getconf _NPROCESSORS_ONLN)" exited with 2."

For full log please see this https://travis-ci.com/github/sanjaymsh/icecream/jobs/403169892

Please have a look on this.

Thanks !!

**Comment by deriamis** [comment]
Based on a little research, I think the problem here is either an old version of `asciidoc` or the Docbook XSL stylesheets not being available locally and remote connections being either denied or very latent. It probably isn't an issue with the Icecream codebase. Please try looking into the potential issues I've mentioned to see if changing one of them fixes your problem.
